### ISSUE TITLE
"could not resolve host" ?

### ISSUE THREAD

**Issue by andrewcstewart** [Cecilapp/GitHub-Pages-deploy#12]
Hi there. I'm getting the following error:

```bash
### Started deploy to myorg/myrepo/gh-pages
fatal: unable to access 'https://***/': Could not resolve host: ***
fatal: Too many arguments.
```

I have both `secrets.EMAIL` and `secrets.ACCESS_TOKEN` set. The only thing that's possibly weird here is that this repo is under an organization.

I am sorta wondering if this might be semi-related to #9 ?

Anyhow, just trying to troubleshoot and curious if anything obvious occurs to you. Thanks!

**Comment by LukasWallrich** [comment]
Same issue here - and I am not in an organisation. Any ideas? Thanks!

```
### Started deploy to LukasWallrich/StMarysSocPsy/gh-pages
fatal: unable to access 'https://***/': Could not resolve host: ***
fatal: Too many arguments.
```

**Comment by ArnaudLigny** [comment]
Please try the version 3.0.0: https://github.com/Cecilapp/GitHub-Pages-deploy#news.
