### ISSUE TITLE
Passing a custom commit message

### ISSUE THREAD

**Issue by nhejazi** [Cecilapp/GitHub-Pages-deploy#17]
I'm pretty new to GH actions and am in the process of migrating from alternatives like Travis. I've found this deploy action very useful for easily publishing sites to the `gh-pages` and have been using it for publishing teaching materials (e.g., https://github.com/tlverse/enar2021-workshop/blob/master/.github/workflows/bookdown.yml#L90).

When working with Travis-CI, I used to be able to tag the automated commits to `gh-pages` with the commit hash that generated the HTML source and found this useful for documentation, debugging, etc. I can see how this might work generically with GH Actions as well, but couldn't find a way with this particular action --- if there isn't already one (perhaps I've missed it in the documentation), would it be possible to add a commit entry accessible via `with:` (e.g., as with `email`, `build_dir`) that can be overwritten with a custom commit message?

**Comment by angelobanse** [comment]
+1

**Comment by ArnaudLigny** [comment]
This new feature have been added in the latest release (https://github.com/Cecilapp/GitHub-Pages-deploy/releases/tag/3.2.0). Thanks to @angelobanse! 👍
